site_name: 'Getting Started with AWS'
site_url: https://example.com/
nav:
  - Home: index.md
# theme: readthedocs
# theme:
#   name: material
#   palette:
#     scheme: default
#     primary: black
#   features:
#     - toc.integrate